import React from 'react'

const Skills = () => {
  return (
    <section id='skills'>
        <marquee width="100%" direction="right" height="80px" scrollamount="18"><h1>NEXT JS _ REACT _ REDUX _ JAVASCRIPT _ NEXT JS _ REACT _ REDUX _ JAVASCRIPT _ NEXT JS _ REACT _ REDUX _ JAVASCRIPT _ NEXT JS _ REACT _ REDUX _ JAVASCRIPT _ NEXT JS _ REACT _ REDUX _ JAVASCRIPT _ NEXT JS _ REACT _ REDUX _ JAVASCRIPT _ NEXT JS _ REACT _ REDUX _ JAVASCRIPT _ NEXT JS _ REACT _ REDUX _ JAVASCRIPT _ NEXT JS _ REACT _ REDUX _ JAVASCRIPT _ NEXT JS _ REACT _ REDUX _ JAVASCRIPT</h1></marquee>
        <marquee width="100%" direction="left" height="80px" scrollamount="30"><h1>TAILWIND _ BOOTSTRAP _ SCSS _ STYLED COMPONENTS _ SHADCN/UI _ TAILWIND _ BOOTSTRAP _ SCSS _ STYLED COMPONENTS _ SHADCN/UI _ TAILWIND _ BOOTSTRAP _ SCSS _ STYLED COMPONENTS _ SHADCN/UI _ TAILWIND _ BOOTSTRAP _ SCSS _ STYLED COMPONENTS _ SHADCN/UI _ TAILWIND _ BOOTSTRAP _ SCSS _ STYLED COMPONENTS _ SHADCN/UI _ TAILWIND _ BOOTSTRAP _ SCSS _ STYLED COMPONENTS _ SHADCN/UI _ TAILWIND _ BOOTSTRAP _ SCSS _ STYLED COMPONENTS _ SHADCN/UI _ TAILWIND _ BOOTSTRAP _ SCSS _ STYLED COMPONENTS _ SHADCN/UI _ TAILWIND _ BOOTSTRAP _ SCSS _ STYLED COMPONENTS _ SHADCN/UI _ TAILWIND _ BOOTSTRAP _ SCSS _ STYLED COMPONENTS _ SHADCN/UI</h1></marquee>
        <marquee width="100%" direction="right" height="80px" scrollamount="30"><h1>HTML _ CSS _ FIGMA _ WEBFLOW _ VS CODE _ HTML _ CSS _ FIGMA _ WEBFLOW _ VS CODE _ HTML _ CSS _ FIGMA _ WEBFLOW _ VS CODE _ HTML _ CSS _ FIGMA _ WEBFLOW _ VS CODE _ HTML _ CSS _ FIGMA _ WEBFLOW _ VS CODE _ HTML _ CSS _ FIGMA _ WEBFLOW _ VS CODE _ HTML _ CSS _ FIGMA _ WEBFLOW _ VS CODE _ HTML _ CSS _ FIGMA _ WEBFLOW _ VS CODE _ HTML _ CSS _ FIGMA _ WEBFLOW _ VS CODE _ HTML _ CSS _ FIGMA _ WEBFLOW _ VS CODE</h1></marquee>
    </section>
  )
}

export default Skills